---
title: "Tutorial Challenges"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## No. 1

```{r}
par( mfrow=c(1,1) )
q <- c(1:10)
plot(q, q, 
     xlab="x axis", ylab="y axis", main="challenge1")
abline(h=5, lty=2, col="blue")
abline(v=10, lty="dotted", col="green")
arrows(1,1, 4,4, angle=120, col="dark green")
text(8,9, "ABCD")
rect(1, 6, 4, 9, density=20, col="gold", angle=180)
legend(8, 3, c("P", "Q", "R"), lty=1:3, col=1:3)
```

## No. 2

```{r}
par( mfrow=c(1,1) )
layout( matrix(c(1,1,2,3), nrow=2, byrow=F) )
plot(cars, col="blue")
rug(cars$dist, side=2)

linearMod <- lm(dist ~ speed, data=cars)
abline(linearMod$coefficients[1], linearMod$coefficients[2], lty=2, col="green")

text(cars[10,], "Cars", srt=60)
hist(cars$speed, col="green3")
hist(cars$dist, col="red3")

```

## No. 3


```{r}
par( mfrow=c(1,1) )
if(!require(raster)) install.packages("raster")
library(raster)

kor1 <- getData("GADM", country='KOR', level=1)   # 행정구역 데이터
a <- getData('alt', country='KOR', mask=T)  # 고도 데이터
plot(a)
plot(kor1, add=T)

points(126.5, 35.2, pch=16, col="red")
abline(h=38, col="gray", lwd=2)
```


## No. 4

```{r}
if(!require(ggplot2)) install.packages("ggplot2") 
library(ggplot2)
p <- ggplot( data=mtcars, aes(x=disp, y=mpg))
p <- p + geom_point( aes(color=hp, size=wt) )
p <- p + geom_text( aes(x=disp+2, y=mpg+2, size=2, hjust=0, label=rownames(mtcars), color=hp) )
p + facet_grid( ~ cyl)
head(mtcars)

```

